In [5]:
%pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
  Using cached absl_py-2.5.0-py3-none-any.whl.metadata (3.3 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
  Using cached gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
  Using cached termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 3.4/351.2 MB 21.0 MB/s eta 0:00:17
    --------------------------------------- 5.8/351.2 MB 15.6 MB/s eta 0:00:23
    --------------------------------------- 8.4/351.2 MB 14.5 MB/s eta 0:00:24
   - -------------------------------------- 10.0/351.2 MB 12.4

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.51.0 requires protobuf<7,>=3.20, but you have protobuf 7.36.2 which is incompatible.


In [9]:
from tensorflow.keras.preprocessing.text import one_hot

In [10]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [11]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [12]:
## Define the vocabulary size
voc_size=10000

In [13]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [14]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6146, 4562, 622, 7195],
 [6146, 4562, 622, 9276],
 [6146, 8403, 622, 6796],
 [9303, 6314, 6696, 6893, 259],
 [9303, 6314, 6696, 6893, 6192],
 [2757, 6146, 8448, 622, 4225],
 [9634, 5476, 6304, 6893]]

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [15]:
import numpy as np

In [16]:
##basic the our RNN model needs sequences in a batch to have the same length 
## pad_sequence() : add padding or truncate sequence to a fixed lenght.
## paddig='pre': add zeros at the begining of shorter sequences.
## maxlen = sent_length: make every sequence exactly 8 element long  

sent_length = 8

embbeding_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embbeding_docs)

[[   0    0    0    0 6146 4562  622 7195]
 [   0    0    0    0 6146 4562  622 9276]
 [   0    0    0    0 6146 8403  622 6796]
 [   0    0    0 9303 6314 6696 6893  259]
 [   0    0    0 9303 6314 6696 6893 6192]
 [   0    0    0 2757 6146 8448  622 4225]
 [   0    0    0    0 9634 5476 6304 6893]]


In [17]:
dim = 10

In [18]:
model = Sequential()

model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile("adam",'mse')

e:\Deep Learning\.venv\Lib\site-packages\keras\src\layers\core\embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [20]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
#Embedding layer, but Keras hasn't established the model's complete input shape yet. thats why do below step

#Import Sequential to create a neural network  model 
from tensorflow.keras.models import Sequential

#Import Embedding: to covert the wordID into dense vectotrs
#Impot Input : to define the shape of input data
from tensorflow.keras.layers import Embedding,Input

#create sequential empty neural network model 
model = Sequential()

#Define the input shape
# Each sentence contains a fixed number of word IDs
# sent_length = number of word IDs in each sentence
model.add(Input(shape=(sent_length,)))

# Add the Embedding layer
model.add(
    Embedding(
        input_dim=voc_size, # Total number of words in the vocabulary
        output_dim=dim # Number of values in each word vector
    )
)

# Configure the model for training
# adam = optimizer that updates model weights
# mse = Mean Squared Error, a loss function
model.compile(optimizer='adam',loss='mse')

# Display the model architecture, output shapes, and parameters
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [27]:
# Generate output vectors for the input sentences 
prediction = model.predict(embbeding_docs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step


In [29]:
print(prediction)
print(prediction.shape)

[[[ 1.52127407e-02 -3.18509825e-02  3.72292511e-02  3.30293179e-03
   -4.66817021e-02  2.67525651e-02 -3.35561633e-02 -4.39822935e-02
   -4.53501604e-02 -8.42023641e-04]
  [ 1.52127407e-02 -3.18509825e-02  3.72292511e-02  3.30293179e-03
   -4.66817021e-02  2.67525651e-02 -3.35561633e-02 -4.39822935e-02
   -4.53501604e-02 -8.42023641e-04]
  [ 1.52127407e-02 -3.18509825e-02  3.72292511e-02  3.30293179e-03
   -4.66817021e-02  2.67525651e-02 -3.35561633e-02 -4.39822935e-02
   -4.53501604e-02 -8.42023641e-04]
  [ 1.52127407e-02 -3.18509825e-02  3.72292511e-02  3.30293179e-03
   -4.66817021e-02  2.67525651e-02 -3.35561633e-02 -4.39822935e-02
   -4.53501604e-02 -8.42023641e-04]
  [-2.81529501e-03  2.92035975e-02  4.79245186e-03  9.21415165e-03
    5.93088940e-03 -1.38527974e-02 -2.89726257e-02  3.93893830e-02
    2.80376710e-02 -7.47926533e-05]
  [-3.63353975e-02 -1.18047707e-02  4.29157950e-02  1.55232884e-02
   -2.14297660e-02 -4.38486598e-02  9.55568627e-03  4.41550277e-02
   -6.66832924e-

In [30]:
embbeding_docs[0]

array([   0,    0,    0,    0, 6146, 4562,  622, 7195], dtype=int32)